/**
 * Provides notification delivery through the WhatsApp service.
 * Implements the NotificationMedium interface so it can be used
 * by AlertSystem as a notification channel.
 *
 * Note: AI assistance was used to review JavaDoc formatting and
 * documentation style for CSC6301 Module 5.
 * 
 * Prompt: exported the file and asked "can you generate the documentation for this file?"
 * 
 * Ensurement: read the documentation generated by AI to make sure it aligns with 
 * what the code is intended by the developer.
 *
 * @author Amane Godo
 * @version 1.0
 */
public class WhatsAppService implements NotificationMedium {
    /**
     * Constructs a WhatsAppService object.
     */
    public WhatsAppService() {
    }

    /**
     * Sends a notification message using the WhatsApp service.
     *
     * @param message the message to be delivered
     */
    @Override
    public void send(String message) {
        System.out.println("[WhatsApp] Sending message: " + message);
    }
}